INSERT INTO ITEM_OPTIONS(PRICE, STATUS, CREATED_DATE) VALUES(200, 'A', NOW());
INSERT INTO ITEM_OPTIONS(PRICE, STATUS, CREATED_DATE) VALUES(180, 'A', NOW());
INSERT INTO ITEM_OPTIONS(PRICE, STATUS, CREATED_DATE) VALUES(400, 'A', NOW());
INSERT INTO ITEM_OPTIONS(PRICE, STATUS, CREATED_DATE) VALUES(800, 'A', NOW());
INSERT INTO ITEM_OPTIONS(PRICE, STATUS, CREATED_DATE) VALUES(250, 'A', NOW());


INSERT INTO ITEM(ITEM_NAME, STATUS, ITEM_OPTIONS_ID) VALUES('Momo', 'A', 1);
INSERT INTO ITEM(ITEM_NAME, STATUS, ITEM_OPTIONS_ID) VALUES('Chowmein', 'A', 2);
INSERT INTO ITEM(ITEM_NAME, STATUS, ITEM_OPTIONS_ID) VALUES('Chicken Sizzler', 'A', 3);
INSERT INTO ITEM(ITEM_NAME, STATUS, ITEM_OPTIONS_ID) VALUES('Pizza', 'A', 4);
INSERT INTO ITEM(ITEM_NAME, STATUS, ITEM_OPTIONS_ID) VALUES('Burger', 'A', 5);

INSERT INTO PAYMENT(TYPE) VALUES('Cash');

INSERT INTO USER_PASSWORD(PASSWORD, INCORRECT_LOGIN_ATTEMPTS) VALUES('password', 0);
INSERT INTO USER(USER_NAME, USER_PASSWORD_ID) VALUES ('root', 1);

